import { PaginationQuery } from "#/@types/misc";
import Audio, { AudioDocument } from "#/models/audio";
import AutoGeneratedPlaylist from "#/models/autoGeneratedPlaylist";
import History from "#/models/history";
import Playlist from "#/models/playlist";
import User from "#/models/user";
import { getUserPreviousHistory } from "#/utils/helper";
import { RequestHandler } from "express";
import { isValidObjectId, ObjectId, PipelineStage, Types } from "mongoose";

export const updateFollower: RequestHandler = async (
  req,
  res
): Promise<any> => {
  const { profileId } = req.params;
  let status: "added" | "removed";
  if (!isValidObjectId(profileId))
    return res.status(422).json({ message: "Invalid profile id!" });

  const profile = await User.findById(profileId);
  if (!profile) return res.status(404).json({ message: "Profile not found!" });

  const alreadyFollower = await User.findOne({
    _id: profileId,
    followers: req.user.id,
  });

  if (alreadyFollower) {
    // unfollow user
    await User.updateOne(
      { _id: profileId },
      { $pull: { followers: req.user.id } }
    );
    status = "removed";
  } else {
    // follow user
    await User.updateOne(
      { _id: profileId },
      { $addToSet: { followers: req.user.id } }
    );
    status = "added";
  }

  if (status === "added") {
    // update and add the following list
    await User.updateOne(
      { _id: req.user.id },
      { $addToSet: { following: profileId } }
    );
  }

  if (status === "removed") {
    // update and remove the following list
    await User.updateOne(
      { _id: req.user.id },
      { $pull: { following: profileId } }
    );
  }

  return res.status(200).json({ status });
};

export const getUploads: RequestHandler = async (req, res): Promise<any> => {
  const { pageNo = "0", limit = "10" } = req.query as PaginationQuery;

  const data = await Audio.find({ owner: req.user.id })
    .skip(parseInt(limit) * parseInt(pageNo))
    .limit(parseInt(limit))
    .sort("-createdAt");

  const audios = data.map((item) => {
    return {
      id: item._id,
      title: item.title,
      about: item.about,
      file: item.file.url,
      poster: item.poster?.url,
      date: item.createdAt,
      owner: {
        id: req.user.id,
        name: req.user.name,
      },
    };
  });

  return res.status(200).json({ audios });
};

export const getPublicUploads: RequestHandler = async (
  req,
  res
): Promise<any> => {
  const { pageNo = "0", limit = "10" } = req.query as PaginationQuery;
  const { profileId } = req.params;

  if (!isValidObjectId(profileId))
    return res.status(422).json({ message: "Invalid profile id!" });

  const data = await Audio.find({ owner: profileId })
    .skip(parseInt(limit) * parseInt(pageNo))
    .limit(parseInt(limit))
    .sort("-createdAt")
    .populate<AudioDocument<{ name: string; _id: ObjectId }>>("owner");

  const audios = data.map((item) => {
    return {
      id: item._id,
      title: item.title,
      about: item.about,
      file: item.file.url,
      poster: item.poster?.url,
      date: item.createdAt,
      owner: {
        id: item.owner._id,
        name: item.owner.name,
      },
    };
  });

  return res.status(200).json({ audios });
};

export const getPublicProfile: RequestHandler = async (
  req,
  res
): Promise<any> => {
  const { profileId } = req.params;

  if (!isValidObjectId(profileId))
    return res.status(422).json({ message: "Invalid profile id!" });

  const user = await User.findById(profileId);
  if (!user) return res.status(422).json({ message: "User not found!" });

  return res.json({
    profile: {
      id: user._id,
      name: user.name,
      followers: user.followers.length,
      avatar: user.avatar?.url,
    },
  });
};

export const getPublicPlaylist: RequestHandler = async (
  req,
  res
): Promise<any> => {
  const { pageNo = "0", limit = "10" } = req.query as PaginationQuery;
  const { profileId } = req.params;

  if (!isValidObjectId(profileId))
    return res.status(422).json({ message: "Invalid profile id!" });

  const playlists = await Playlist.find({
    owner: profileId,
    visibility: "public",
  })
    .skip(parseInt(limit) * parseInt(pageNo))
    .limit(parseInt(limit))
    .sort("-createdAt");

  if (!playlists) return res.status(200).json({ playlist: [] });

  return res.status(200).json({
    playlists: playlists.map((item) => {
      return {
        id: item._id,
        title: item.title,
        itemCount: item.items.length,
        visibility: item.visibility,
      };
    }),
  });
};

export const getRecommendedByProfile: RequestHandler = async (
  req,
  res
): Promise<any> => {
  const user = req.user;

  let matchOptions: PipelineStage.Match = {
    $match: { _id: { $exists: true } },
  };

  if (user) {
    // then we want to send by the profile
    const category = await getUserPreviousHistory(req);

    const categories = category;
    if (categories.length) {
      matchOptions = {
        $match: { category: { $in: categories } },
      };
    }
  }

  // if user not login send the generic audios
  const audios = await Audio.aggregate([
    matchOptions,
    {
      $sort: { "likes.count": -1 },
    },
    { $limit: 10 },
    {
      $lookup: {
        from: "users",
        localField: "owner",
        foreignField: "_id",
        as: "owner",
      },
    },
    { $unwind: "$owner" },
    {
      $project: {
        _id: 0,
        id: "$_id",
        title: "$title",
        category: "$category",
        about: "$about",
        file: "$file.url",
        poster: "$poster.url",
        owner: {
          name: "$owner.name",
          id: "$owner._id",
        },
      },
    },
  ]);

  return res.status(200).json({ audios });
};

export const getAutoGeneratedPlaylist: RequestHandler = async (
  req,
  res
): Promise<any> => {
  // find out 5 playlist

  const [result] = await History.aggregate([
    { $match: { owner: req.user.id } },
    { $unwind: "$all" },
    { $group: { _id: "$all.audio", items: { $addToSet: "$all.audio" } } },
    { $sample: { size: 10 } },
    { $group: { _id: null, items: { $push: "$_id" } } },
  ]);

  const title = "Mix 10";

  if (result) {
    await Playlist.updateOne(
      { owner: req.user.id, title },
      { $set: { title, items: result.items, visibility: "auto" } },
      { upsert: true }
    );
  }

  const category = await getUserPreviousHistory(req);

  // auto generated playlist
  let matchOptions: PipelineStage.Match = {
    $match: { _id: { $exists: true } },
  };

  if (category.length) {
    matchOptions = { $match: { title: { $in: category } } };
  }

  const autoGeneratedPlaylist = await AutoGeneratedPlaylist.aggregate([
    matchOptions,
    { $sample: { size: 4 } },
    {
      $project: {
        _id: 0,
        id: "$_id",
        title: "$title",
        itemCount: { $size: "$items" },
      },
    },
  ]);

  const playlist = await Playlist.findOne({ owner: req.user.id, title });

  const finalList = autoGeneratedPlaylist.concat({
    id: playlist?._id,
    title: playlist?.title,
    itemsCount: playlist?.items.length,
  });

  return res.status(200).json({ playlist: finalList });
};

export const getFollowerProfile: RequestHandler = async (
  req,
  res
): Promise<any> => {
  const { limit = "10", pageNo = "0" } = req.query as PaginationQuery;

  const [result] = await User.aggregate([
    { $match: { _id: req.user.id } },
    {
      $project: {
        followers: {
          $slice: [
            "$followers",
            parseInt(pageNo) * parseInt(limit),
            parseInt(limit),
          ],
        },
      },
    },
    { $unwind: "$followers" },
    {
      $lookup: {
        from: "users",
        localField: "followers",
        foreignField: "_id",
        as: "userInfo",
      },
    },
    { $unwind: "$userInfo" },
    {
      $group: {
        _id: null,
        followers: {
          $push: {
            id: "$userInfo._id",
            name: "$userInfo.name",
            avatar: "$userInfo.avatar.url",
          },
        },
      },
    },
  ]);

  if (!result) return res.status(200).json({ followers: [] });

  res.status(200).json({ followers: result.followers });
};

export const getFollowerProfilePublic: RequestHandler = async (
  req,
  res
): Promise<any> => {
  const { limit = "10", pageNo = "0" } = req.query as PaginationQuery;
  const { profileId } = req.params;

  if (!isValidObjectId(profileId))
    return res.status(422).json({ message: "Invalid profile id!" });

  const [result] = await User.aggregate([
    { $match: { _id: new Types.ObjectId(profileId) } },
    {
      $project: {
        followers: {
          $slice: [
            "$followers",
            parseInt(pageNo) * parseInt(limit),
            parseInt(limit),
          ],
        },
      },
    },
    { $unwind: "$followers" },
    {
      $lookup: {
        from: "users",
        localField: "followers",
        foreignField: "_id",
        as: "userInfo",
      },
    },
    { $unwind: "$userInfo" },
    {
      $group: {
        _id: null,
        followers: {
          $push: {
            id: "$userInfo._id",
            name: "$userInfo.name",
            avatar: "$userInfo.avatar.url",
          },
        },
      },
    },
  ]);

  if (!result) return res.status(200).json({ followers: [] });

  res.status(200).json({ followers: result.followers });
};

export const geFollowingProfile: RequestHandler = async (
  req,
  res
): Promise<any> => {
  const { limit = "10", pageNo = "0" } = req.query as PaginationQuery;

  const [result] = await User.aggregate([
    { $match: { _id: req.user.id } },
    {
      $project: {
        following: {
          $slice: [
            "$following",
            parseInt(pageNo) * parseInt(limit),
            parseInt(limit),
          ],
        },
      },
    },
    { $unwind: "$following" },
    {
      $lookup: {
        from: "users",
        localField: "following",
        foreignField: "_id",
        as: "userInfo",
      },
    },
    { $unwind: "$userInfo" },
    {
      $group: {
        _id: null,
        followings: {
          $push: {
            id: "$userInfo._id",
            name: "$userInfo.name",
            avatar: "$userInfo.avatar.url",
          },
        },
      },
    },
  ]);

  if (!result) return res.status(200).json({ following: [] });

  res.status(200).json({ followings: result.followings });
};

export const getPlaylistAudios: RequestHandler = async (
  req,
  res
): Promise<any> => {
  const { limit = "10", pageNo = "0" } = req.query as PaginationQuery;
  const { playlistId } = req.params;

  if (!isValidObjectId(playlistId))
    return res.status(422).json({ message: "Invalid playlist id!" });

  const aggregationLogic = [
    {
      $match: {
        _id: new Types.ObjectId(playlistId),
        visibility: { $ne: "private" },
      },
    },
    {
      $project: {
        items: {
          $slice: [
            "$items",
            parseInt(pageNo) * parseInt(limit),
            parseInt(limit),
          ],
        },
        title: "$title",
      },
    },
    { $unwind: "$items" },
    {
      $lookup: {
        from: "audios",
        localField: "items",
        foreignField: "_id",
        as: "audios",
      },
    },
    { $unwind: "$audios" },
    {
      $lookup: {
        from: "users",
        localField: "audios.owner",
        foreignField: "_id",
        as: "ownerInfo",
      },
    },
    { $unwind: "$ownerInfo" },
    {
      $group: {
        _id: {
          id: "$id",
          title: "$title",
        },
        audios: {
          $push: {
            id: "$audios._id",
            title: "$audios.title",
            about: "$audios.about",
            category: "$audios.category",
            file: "$audios.file.url",
            poster: "$audios.poster.url",
            owner: { name: "$ownerInfo.name", id: "$ownerInfo._id" },
          },
        },
      },
    },
    {
      $project: {
        _id: 0,
        id: "$_id.id",
        title: "$_id.title",
        audios: "$$ROOT.audios",
      },
    },
  ];

  const [playlistResult] = await Playlist.aggregate(aggregationLogic);

  if (!playlistResult) {
    const [autoPlaylistResult] = await AutoGeneratedPlaylist.aggregate(
      aggregationLogic
    );
    return res.json({ list: autoPlaylistResult });
  }

  return res.json({ list: playlistResult });
};

export const getPrivatePlaylistAudios: RequestHandler = async (
  req,
  res
): Promise<any> => {
  const { limit = "10", pageNo = "0" } = req.query as PaginationQuery;
  const { playlistId } = req.params;

  if (!isValidObjectId(playlistId))
    return res.status(422).json({ message: "Invalid playlist id!" });

  const aggregationLogic = [
    {
      $match: {
        _id: new Types.ObjectId(playlistId),
        owner: req.user.id,
      },
    },
    {
      $project: {
        items: {
          $slice: [
            "$items",
            parseInt(pageNo) * parseInt(limit),
            parseInt(limit),
          ],
        },
        title: "$title",
      },
    },
    { $unwind: "$items" },
    {
      $lookup: {
        from: "audios",
        localField: "items",
        foreignField: "_id",
        as: "audios",
      },
    },
    { $unwind: "$audios" },
    {
      $lookup: {
        from: "users",
        localField: "audios.owner",
        foreignField: "_id",
        as: "ownerInfo",
      },
    },
    { $unwind: "$ownerInfo" },
    {
      $group: {
        _id: {
          id: "$id",
          title: "$title",
        },
        audios: {
          $push: {
            id: "$audios._id",
            title: "$audios.title",
            about: "$audios.about",
            category: "$audios.category",
            file: "$audios.file.url",
            poster: "$audios.poster.url",
            owner: { name: "$ownerInfo.name", id: "$ownerInfo._id" },
          },
        },
      },
    },
    {
      $project: {
        _id: 0,
        id: "$_id.id",
        title: "$_id.title",
        audios: "$$ROOT.audios",
      },
    },
  ];

  const [playlistResult] = await Playlist.aggregate(aggregationLogic);

  if (!playlistResult) {
    const [autoPlaylistResult] = await AutoGeneratedPlaylist.aggregate(
      aggregationLogic
    );
    return res.json({ list: autoPlaylistResult });
  }

  return res.json({ list: playlistResult });
};

export const getIsFollowing: RequestHandler = async (
  req,
  res
): Promise<any> => {
  const { profileId } = req.params;
  if (!isValidObjectId(profileId))
    return res.status(422).json({ message: "Invalid profile id!" });

  const user = await User.findOne({ _id: profileId, followers: req.user.id });

  return res.status(200).json({ status: user ? true : false });
};
